### ISSUE TITLE
Config is set separately in BaseIndex after already being set on SolrCoreService

### ISSUE THREAD

**Issue by sig-peggy** [signify-nz/silverstripe-solr#2]
In the BaseIndex `__construct` function, the config is reset to the yaml settings when it's also already set when the SolrCoreService is created. This means the client options are being set twice when they don't need to be, and also makes it harder to override the yaml settings if that's required (e.g. to replace some with environment variables).
lines 109-112:
``` php
$config = Config::inst()->get(SolrCoreService::class, 'config');
$config['endpoint'] = $this->getConfig($config['endpoint']);
$this->client = (new SolrCoreService())->getClient();
$this->client->setOptions($config);
```
Instead, the options already set once when the SolrCoreService is created can be used as the base that the 'endpoint' is added to. This makes sure that any changes to the SolrCoreService are reflected in the Index.

**Comment by sig-mmiddleton** [comment]
Resolved in 2.1.0
