### ISSUE TITLE
SpellcheckRetry should be optional

### ISSUE THREAD

**Issue by sig-peggy** [signify-nz/silverstripe-solr#3]
The `doSearch` function in BaseIndex will always follow the spellcheck suggestions if spellcheck is turned on and the results are empty, but this is not always the preferred behaviour.

This is particularly problematic in combination with synonyms, where the original search term has no results itself, which means a spellcheck suggestion can be returned, but if the original search term has results from an associated synonym then the results returned are _not_ from the spellcheck suggested term.

There is a `followSpellcheck` option on the BaseQuery, but this appears to be used to force following the spellcheck even when there are results for the original term, rather than allowing it when there are no results. There is a note with the relevant variable that implies this was not it's intended purpose, but documentation on the BaseIndex doRetry function is contradictory. 
BaseQuery - $followSpellcheck documentation:
``` php
/**
 * @var bool Follow spellchecking if there are no results
 */
 protected $followSpellcheck = false;
```
BaseIndex - doRetry() documentation:
``` php
\**
 * Check if the query should be retried with spellchecking
 * Conditions are:
 * It is not already a retry with spellchecking
 * Spellchecking is enabled
 * If spellchecking is enabled and nothing is found OR it should follow spellchecking none the less
 * There is a spellcheck output
 * /
```

Note: As-is, overriding the `spellcheckRetry` function to skip the retry means that the `updateSearchResults` extension point is skipped as it does not call `doSearch` again.

Expected behaviour: We should be able to get spellcheck _suggestions_ without necessarily following that suggestion when the original term has no results. If the `$followSpellcheck` setting is meant to apply only if there are no results, then the `doRetry` function should reflect that; or if the `$followSpellcheck` setting is meant to apply even if there are results, then the documentation for the variable should reflect that and an additional setting should be added to allow better control of the spellcheck behaviour.

**Comment by sig-mmiddleton** [comment]
Resolved in 2.1.0
