### ISSUE TITLE
Changing page type creates duplicate record in index

### ISSUE THREAD

**Issue by sig-peggy** [signify-nz/silverstripe-solr#4]
When an existing page is already in the index and then the page type is changed, this creates a new record in the index without removing the old one. This means that the page can appear twice in search results, and that the previous version of the page becomes disconnected from any real record so it can never be updated or deleted without a full re-index.

Expected behaviour: when a page type changes, the previous record should be removed from the index before the new record is created.

**Comment by sig-mmiddleton** [comment]
Resolved in 2.1.0
