### ISSUE TITLE
Fix permissions for admin area

### ISSUE THREAD

**Issue by sig-peggy** [signify-nz/silverstripe-solr#5]
Some content authors may need access to the 'Synonyms' tab in the 'Search' admin area of the CMS, but should not see the 'Solr Logs' and 'Dirty Classes' tabs.

Currently, there are permission options available for 'View Solr logs' and 'Delete Solr logs' but these options are not used to determine whether a member can do those actions. There are no separate permissions for the other tabs in the admin area, and viewing the models does not inherit from the default "Access to 'Search' section" permission. This means that a Content Author can be given permission to access the section, and will be able to see all three tabs, but the gridfields in every tab will appear empty as they do not have permission to view the models.

**Expected behaviour**
- If a Member has access to the Search section, they should be able to see the Synonyms tab and the Synonym items without additional permissions.
- There should be additional permissions added to be able to view the 'Dirty Classes' - there should not be any permissions available to create/delete/edit these. If a Member does not have permissions to view the 'DirtyClass' objects, then they should not see the 'Dirty Classes' tab in the admin area.
- The existing permissions for delete and view Solr logs should be implemented to act as per their descriptions. If a Member does not have permissions to view 'SolrLog' objects, then they should not see the 'Solr Logs' tab in the admin area
- Optional - An additional permission could also be added for editing Synonyms. The view permission can inherit from the overall section permission, but there may be cases where it would be valid to give some Members permission to see the Synonyms without being able to edit them. If it's decided that this additional permission is not required then the edit/create/delete permissions for Synonyms should also inherit from the section permission.

**Comment by sig-mmiddleton** [comment]
Resolved in 2.1.0
