### ISSUE TITLE
Docs need to be updated

### ISSUE THREAD

**Issue by sig-mmiddleton** [signify-nz/silverstripe-solr#7]
The docs will need to be updated before publishing on packagist.

We need to:

- Remove/replace incorrect references to the original firesphere module
- Remove references to the original owners as active maintainers (but keep reference to them as authors)
- Remove the CircleCI integration
- Remove any calls for sponsorship, financial support etc
- Remove/replace old contact details referring to the original authors
- Ensure the composer.json file contains the correct information
- Ensure that the module documentation aligns with best practice

Once the above is complete, this module should be ready for publishing on packagist.

**Comment by sig-peggy** [comment]
Changes completed under https://github.com/signify-nz/silverstripe-solr-search/issues/2 instead. This repo to be archived
